spring: 
   application.name: account-service
   cloud.config:
      discovery:
         enabled: true
         serviceId: account-service
         
eureka:
 client:
   serviceUrl:
     defaultZone: http://localhost:7001/eureka/
   registryFetchIntervalSeconds: 1
 instance:
   leaseRenewalIntervalInSeconds: 1